---
title: "rabies.qmd"
format: html
editor: visual
---

## Rabies project

You are receiving a dataset from the New York State Department of Health that shows test results for specimens submitted to be tested for rabies.

Your goals are twofold:

-   To practice using the material from Chapter 3 of GSWR and
-   To learn something about rabies in New York.

## Set things up and read in the data

Add the code to set up the workspace

```{r}
rm(list =ls())
library(tidyverse)
library(here)
```

Now read in the data and name it as an object called `rabies`.

## Get started

Use a combination of filter, select, slice, arrange, group_by, summarize, mutate or any other functions covered in Chapter 3 of GSWR to answer the following questions about this data set.

1.  After you read in all of the data, create a new data frame called rabies that includes just the first 7 columns (omit latitude, longitude and geocode information) from the original dataset.

2.  Create a new column in your dataset called "Percent_pos" and set it equal to (number of positive samples / number of samples)\*100.

*After you have taken care of tasks 1 and 2, you may wish to divide up the work among your group members by assigning different questions to different team members. **Each team member should work from a different branch on the project and should submit their suggested changes via a pull request.***

3.  In what year was the highest total number of sample submissions received? (Hint: you might want the `sum()` function)

4.  In what year and in what county was the highest positive number of samples received?

5.  How many rows of data are there that include submissions from bats for which the samples were positive for rabies? For which the samples were not positive for rabies?

6.  How many animal types were there for which, in instances in which there were more than 4 samples submitted at a time, the percent of positive samples was greater than 50%?

7.  Create a new dataset that includes only data from St. Lawrence County and name it SLC. Next, calculate, by Animal.Classification, the total number of submissions per year, the total number of positive submissions per year, and then the percent positive per year based on those two totals. Save your results in a new data frame called SLC_animals.

8.  Create a new dataset that includes only data from St. Lawrence County from 2020 to present. Name the dataset `SLC_recent`.

9.  What was the animal type for which the highest percent of submitted samples tested positive by year in your St. Lawrence County dataset? What is the average percent positive by year?

When you have finished working on your questions, save your changes and commit them. Working from your branch (and not *main*), push your changes to your repository and then open a Pull Request to have the changes incorporated into your group repository.
